name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2
    - name: Install web-server
      run: |
        curl -s --remote-name-all https://raw.githubusercontent.com/eschulte/emacs-web-server/master/web-server{,-status-codes}.el
        emacs -Q --batch -L . -f batch-byte-compile web-server*.el
    - name: Byte compile
      run: |
        emacs -Q --batch -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile another-emacs-server.el
    - name: Try the server
      run: |
        emacs -Q --daemon
        emacsclient --eval "(push \"$PWD\" load-path)"
        emacsclient --eval "(require 'another-emacs-server)"
        emacsclient --eval '(another-emacs-server)'
        curl -s -d '{"eval": "emacs-version"}' -H "Content-Type: application/json" localhost:7777
